### ISSUE TITLE
Port for 1.19.2?

### ISSUE THREAD

**Issue by ghost** [Estecka/mc-Preferred-Gamerules#1]
Really loves this mod! It's great for modpacks and just for quality of life. Would be nice if it had a port for 1.19-!

**Comment by Estecka** [comment]
Hi,

You should test whether the current jar works on this version.

I marked the mod for the range 1.19.4-1.20.4 because it's the only versions I _tested_. But since the same jar already works for all of them, it will likely work for other nearby versions of Minecraft.

The current jar doesn't declare any hard dependency on >=1.19.4, so you should be able to test this just by installing it normally.

**Comment by ghost** [comment]
Oh, ok! Thanks!

**Comment by ghost** [comment]
Yep, works fine on 1.19.2 from what I can see. Sorry for bothering about that.

**Comment by Estecka** [comment]
No problem, I know it's not usual for other mods to handle multiple versions that way. Even I only do this for the simplest ones.
